### ISSUE TITLE
[Bug]: Cannot access OPENAI_API_KEY in the .env file

### ISSUE THREAD

**Issue by ce7in** [joshembling/laragenie#4]
### What happened?

The API key and Organization variables are already defined in the .env file. There is no problem here because I can use OpenAI PHP SDK and Laravel package properly. It also works on the Tinker package for PhpStorm. However, something needs to be fixed when I try to use Laragenie. It throws an error like the one below:

![image](https://github.com/joshembling/laragenie/assets/6667035/c6f5429b-5fd9-46ad-a553-b0b405f2fe4d)

What might be the problem?

Note: Laragenie is a good package idea that I wanted to develop. You were the first. Congratulations!

### How to reproduce the bug

I have tried to determine whether the SDK sees the env variable, and I consider that OpenAI SDK doesn't see it. I don't know what is the problem.

### Package Version

1.0.6

### PHP Version

8.2.13

### Laravel Version

10.38.1

### Which operating systems does with happen with?

Linux

**Comment by joshembling** [comment]
Can you send me a copy of your env vars you have setup? Obviously remove the keys.

**Comment by PhillipMRE** [comment]
I get the same error
![image](https://github.com/joshembling/laragenie/assets/135060060/8e908706-430e-4604-9e41-8e419cbdcaee)

**Comment by PhillipMRE** [comment]
Figure it out. Rookie mistake.  
Run these and it will fix it. 
```
php artisan config:clear
php artisan cache:clear
```

I still request you add a way to set the openai org though.

**Comment by joshembling** [comment]
> Figured it out. Rookie mistake. Run these and it will fix it.
> 
> ```
> php artisan config:clear
> php artisan cache:clear
> ```
> 
> I still request you add a way to set the openai org though.

Right now, I have no plans to change the way environments are configured, but thanks for your suggestion regarding clearing cache and config.

**Comment by joshembling** [comment]
Closing this issue. As an outcome I've added debugging instructions to documentation.

https://github.com/joshembling/laragenie/releases/tag/v1.0.63
