### ISSUE TITLE
[Idea]: Code generator from our codebase

### ISSUE THREAD

**Issue by adiramardiani** [joshembling/laragenie#5]
### What happened?

First, sorry I write this on bug, i choose template/type but all 404 except Bug Report

### How to reproduce the bug

Soo I not write about reproduce bug here

### Package Version

-

### PHP Version

0

### Laravel Version

0

### Which operating systems does with happen with?

Linux

### Notes

Hi @joshembling 

I like the idea about this package because this is will index my codebase, but currently just have limitation to just ask some question

Using indexing with AI will have benefit to learn our codebase, I think is possible to use this index to automatically generate file to us using our codebase, for example I have pattern Controller > Repository > Service, and export script, import script, testing, routing, blade, for all standar basic CRUD codebase

I think we will have a lot of time to create this pattern, but the pattern just change the `name` right  ? (and other standard repetition)
Just change the file name and some field, this repetition I think can do with AI to generate codebase with AI, this will generate the file, All naming convention, Camel, Snake, Kebab, Pascal Case, etc will convert/generate automatically by AI

To generate just codebase will really help full, I think is enough
But will really cool if AI, can give some input for example field list, so we just give `name` and `field list`, and AI will generate for us
Or just we just create the schema migration, and AI will scan our database to automatically generate field and all relation script
I know this will be some error, but this is must fix with developer itself, the  developer just focus to business process, and all not standard feature for specific purpose

I don't know this still related with this package goal or maybe on another package, but if this can do, will realy cool

*Just my wild imagination hehehe 🤣

**Comment by joshembling** [comment]
Hi @adiramardiani 

Thanks for your suggestion(s), although I'm not 100% certain what you are asking for. 

If you are looking for a way to automatically list index files/directories within your config, I imagine this is already a good use case for Copilot as it can type hint based on previous input. 

Likewise, if you are looking for suggestions on fields within a migration, Copilot will also be able to do that for you in the same way.

I hope this helps.
