### ISSUE TITLE
[Bug]: Instructions are not being passed correctly

### ISSUE THREAD

**Issue by JackWH** [joshembling/laragenie#8]
### What happened?

In `Chatbot.php`, the message content references `laragenie.bot.instruction`, but the config file specifies `laragenie.bot.instructions` (with an 's'). No instructions are therefore passed.

### How to reproduce the bug

See source code

### Package Version

1.0.62

### PHP Version

8.3

### Laravel Version

10

**Comment by joshembling** [comment]
Hi @JackWH 

Thanks for noting this bug. This has now been fixed in the latest release.

https://github.com/joshembling/laragenie/releases/tag/v1.0.63
